
import { createServerClient } from '@supabase/ssr'
import { cookies } from 'next/headers'
import { NextResponse } from 'next/server'
import JSZip from 'jszip'
import { convertHtmlToReact } from '@/lib/html-converter'

// Force dynamic to allow headers/cookies reading
export const dynamic = 'force-dynamic'

export async function GET(request: Request) {
    // Note: We need to parse ID from URL if using app directory dynamic routes differently.
    // But here we are in /api/download/[id] theoretically if we use folder structure. 
    // However, the folder structure is /api/download/route.ts.
    // So we invoke it as /api/download?siteId=...
    
    const { searchParams } = new URL(request.url)
    const siteId = searchParams.get('siteId')

    if (!siteId) {
        return NextResponse.json({ error: 'Missing siteId' }, { status: 400 })
    }

    const cookieStore = await cookies()
    const supabase = createServerClient(
        process.env.NEXT_PUBLIC_SUPABASE_URL!,
        process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
        {
            cookies: {
                getAll() {
                    return cookieStore.getAll()
                },
                setAll(cookiesToSet) {
                    try {
                        cookiesToSet.forEach(({ name, value, options }) =>
                            cookieStore.set(name, value, options)
                        )
                    } catch { }
                },
            },
        }
    )

    // 1. Verify User and Ownership
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) {
        return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const { data: site } = await supabase
        .from('websites')
        .select('*')
        .eq('id', siteId)
        .single()

    if (!site) return NextResponse.json({ error: 'Not found' }, { status: 404 })
    if (site.user_id !== user.id) return NextResponse.json({ error: 'Unauthorized' }, { status: 403 })

    // 2. Fetch HTML content
    const { data: fileData, error: downloadError } = await supabase
        .storage
        .from('websites')
        .download(site.html_path)

    if (downloadError || !fileData) {
        return NextResponse.json({ error: 'Failed to download site files' }, { status: 500 })
    }

    const htmlContent = await fileData.text()

    // 3. Create ZIP
    const zip = new JSZip()
    const folder = zip.folder(`foundrr-site-${siteId}`) || zip

    // A. Raw Code
    folder.file('index.html', htmlContent)

    // B. React/Next.js Version (Extract from Shell)
    // We look for content between logic markers or just the script tag
    let reactCode = ''
    try {
        const match = htmlContent.match(/\/\/ --- GENERATED CODE START ---([\s\S]*?)\/\/ --- GENERATED CODE END ---/)
        if (match && match[1]) {
            reactCode = match[1].trim()
        } else {
            // Fallback: try capturing simple function App
            const appMatch = htmlContent.match(/function App\(\) \{[\s\S]*?^    \}/m)
             if (appMatch) reactCode = appMatch[0]
        }
    } catch(e) {}

    const fullPageTsx = `
'use client'

import React, { useState, useEffect, useRef } from 'react'
import { 
    Camera, Moon, Sun, Menu, X, ArrowRight, Check, Star, 
    ChevronRight, Play, Globe, Shield, Zap, Layout, 
    BarChart, Users, Mail, Phone, MapPin 
} from 'lucide-react'

// You might need to install: npm install lucide-react framer-motion aos

${reactCode}

export default App;
`
    folder.file('page.tsx', fullPageTsx)
    
    // C. Instructions & Metadata
    folder.file('README.md', `# Foundrr AI Generated Site
    
This site was generated by Foundrr AI.

## Contents
- \`index.html\`: The self-contained React HTML file.
- \`page.tsx\`: The extracted React component for Next.js.

## Usage (Next.js)
1. Install dependencies:
   \`npm install lucide-react\`
2. Copy \`page.tsx\` to your \`src/app/\` directory.
`)

    folder.file('package.json', JSON.stringify({
        name: `foundrr-site-${siteId}`,
        version: "1.0.0",
        dependencies: {
            "react": "^18.2.0",
            "react-dom": "^18.2.0",
            "next": "13.4.0",
            "lucide-react": "^0.263.1",
            "clsx": "^2.0.0",
            "tailwind-merge": "^2.0.0"
        }
    }, null, 2))


    // 4. Return ZIP stream
    const zipContent = await zip.generateAsync({ type: 'blob' })
    const arrayBuffer = await zipContent.arrayBuffer()
    const buffer = Buffer.from(arrayBuffer)

    return new NextResponse(buffer, {
        headers: {
            'Content-Type': 'application/zip',
            'Content-Disposition': `attachment; filename="foundrr-${siteId}.zip"`,
        },
    })
}
